### ISSUE TITLE
wait fails with Xs_protocol.Enoent("unwatch")

### ISSUE THREAD

**Issue by talex5** [mirage/ocaml-xenstore#43]
If we try to wait for something and a path we used disappears, ocaml-xenstore raises an exception in an async handler, typically crashing the unikernel.

```
2018-11-04 01:19:13 -00:00: INF [client_net] add client vif {domid=462;device_id=0}
Fatal error: exception Xs_protocol.Enoent("unwatch")
Raised at file "map.ml", line 122, characters 10-25
Called from file "src0/sexp_conv.ml", line 149, characters 10-37
Mirage exiting with status 2
Do_exit called!
```

(from https://github.com/mirage/qubes-mirage-firewall/issues/35)

The error is coming from the XenStore client's `unwatch` function. The firewall doesn't call that directly, but it does call XenStore's `wait` function, which uses it:

https://github.com/mirage/ocaml-xenstore/blob/master/client_lwt/xs_client_lwt.ml#L394

That calls it from an async block, so there's no easy way for the firewall code to catch the exception. It appears that it's just trying to clean up the watches at the end. Presumably if it gets `Enoent` then the watch has already been removed?

**Comment by cfcs** [comment]
@talex5 It sounds to me like ignoring that exception seems fair:
```ocaml
Lwt_list.iter_s (fun p -> try unwatch h p token with Xs_protocol.Enoent "unwatch" -> ())
(elements current_paths)
```

@djs55 / @jonludlam pinging you as you seem to have commits in this repo, this seems to be causing trouble for the qubes-mirage-firewall, can you think of a reason not to ignore this exception?

**Comment by talex5** [comment]
I've had another look at this. It appears that xenstore only returns `ENOENT` if you ask to remove a watch that isn't in the watch list (which should never happen). It doesn't matter whether the file itself exists (you can watch things that don't exist yet):

https://github.com/xen-project/xen/blob/f93abf0315efef861270c25d83c8047fd6a54ec4/tools/xenstore/xenstored_watch.c#L234

Warning: don't try to debug this by testing under Linux (like I did). When you access xenstore on Linux, you go via `/dev/xen/xenbus`, which goes through a proxy/multiplexer in the Linux kernel. This always returns `OK` for unwatch requests, even if the watch didn't exist!

https://github.com/torvalds/linux/blob/43b815c6a8e7dbccb5b8bd9c4b099c24bc22d135/drivers/xen/xenbus/xenbus_dev_frontend.c#L543

I suspect that this error is covering up some other error that would have been reported if the finally block returned. Probably we should log a warning here and return so we can find out what the real error is.

**Comment by cfcs** [comment]
Yeah. We're not much better off with the current situation, so I agree.

**Comment by talex5** [comment]
From https://github.com/mirage/qubes-mirage-firewall/issues/35#issuecomment-567610825, it seems that the underlying error is `E2BIG`:

```
2019-12-17 04:36:41 -00:00: INF [xenstore.client] ** XenStore with unwatch patch **
....
2019-12-19 17:33:22 -00:00: INF [net-xen backend] Frontend asked to close network device dom:3167/vif:0
2019-12-19 17:33:22 -00:00: INF [client_net] client {domid=3167;device_id=0} has gone
2019-12-19 18:25:56 -00:00: INF [client_net] add client vif {domid=3168;device_id=0} with IP 10.137.0.26
2019-12-19 18:25:56 -00:00: ERR [xenstore.client] Error unwatching "/local/domain/3168/device/vif/0/state": Xs_protocol.Enoent("unwatch")
Fatal error: exception Xs_protocol.Error("E2BIG")
Raised at file "map.ml", line 135, characters 10-25
Called from file "sexp_conv.ml", line 147, characters 10-37
Mirage exiting with status 2
Do_exit called!
```

From a quick look at the code:

The fact that we're think we're watching this path but the server doesn't suggests that it was the corresponding `watch` call itself that failed. Looks like this error happens if either the message is too big or we exceed our watch quota. Since the path is quite short, I don't see why the message would be too big, so I assume we're exceeding the quota. Looks like 128 watches per domain is the default limit. Maybe we're leaking watches?
